# Generated by Django 4.2.6 on 2023-10-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_organizer_email_token_organizer_is_email_confirmed'),
        ('events', '0004_alter_comment_ord_user_alter_comment_organizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='ord_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ord_user'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organizer'),
        ),
    ]
