# Generated by Django 4.2.6 on 2023-10-09 12:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ord_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(default='profile/avatarka.jpg', upload_to='profile')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_join', models.DateTimeField(auto_now_add=True)),
                ('email_token', models.IntegerField(blank=True, null=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('recover_token', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('is_busy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(default='profile/avatarka.jpg', upload_to='profile')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_join', models.DateTimeField(auto_now_add=True)),
                ('email_token', models.IntegerField(blank=True, null=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('recover_token', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('is_busy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerUserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('organizer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event_category')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organizer')),
            ],
        ),
        migrations.AddField(
            model_name='organizer',
            name='events',
            field=models.ManyToManyField(through='user.OrganizerUserEvent', to='events.event'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='interests',
            field=models.ManyToManyField(through='user.OrganizerInterests', to='events.event_category'),
        ),
        migrations.CreateModel(
            name='OrdUserInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event_category')),
                ('ord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ord_user')),
            ],
        ),
        migrations.CreateModel(
            name='OrdUserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ord_user')),
            ],
        ),
        migrations.AddField(
            model_name='ord_user',
            name='events',
            field=models.ManyToManyField(through='user.OrdUserEvent', to='events.event'),
        ),
        migrations.AddField(
            model_name='ord_user',
            name='interests',
            field=models.ManyToManyField(through='user.OrdUserInterests', to='events.event_category'),
        ),
    ]
