# Generated by Django 4.2.6 on 2023-10-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='email_token',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
