# Generated by Django 4.2.6 on 2023-10-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_name_organizer_first_name_ord_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ord_user',
            old_name='middle_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='ord_user',
            old_name='name',
            new_name='username',
        ),
    ]
