# Generated by Django 4.2.6 on 2023-10-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_organizer_email_token_organizer_is_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='middle_name',
        ),
    ]
