# Generated by Django 4.2.6 on 2023-10-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_ord_user_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ord_user',
            name='email_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
