# Generated by Django 4.2.6 on 2023-10-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_orduserinterests_ord_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ord_user',
            name='photo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='photo',
            field=models.CharField(max_length=255),
        ),
    ]
