# Generated by Django 4.2.6 on 2023-10-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_ord_user_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ord_user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
