# Generated by Django 4.2.6 on 2023-10-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_ord_user_photo_alter_organizer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ord_user',
            name='photo',
            field=models.ImageField(default='profile/avatarka.jpg', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='photo',
            field=models.ImageField(default='profile/avatarka.jpg', upload_to='profile'),
        ),
    ]
